
class SENSOR_EXCEPTIONS:
   SENSOR_OK                   = 0x0300
   SENSOR_OK_STR               = "Sensor OK"
   SENSOR_INIT                 = 0x0301
   SENSOR_INIT_STR             = "Sensor warming up"
   SENSOR_CAL_NEEDED           = 0x0302
   SENSOR_CAL_NEEDED_STR       = "Calibrate sensor now "
   SENSOR_ERROR                = 0x0303
   SENSOR_ERROR_STR            = "Updating sensor"
   SENSOR_CAL_ERROR            = 0x0304
   SENSOR_CAL_ERROR_STR        = "Calibration error"
   SENSOR_CHANGE_SENSOR        = 0x0305
   SENSOR_CHANGE_SENSOR_STR    = "Change sensor"
   SENSOR_END_OF_LIFE          = 0x0306
   SENSOR_END_OF_LIFE_STR      = "Sensor expired"
   SENSOR_NOT_READY            = 0x0307
   SENSOR_NOT_READY_STR        = "Sensor not ready"
   SENSOR_READING_HIGH         = 0x0308
   SENSOR_READING_HIGH_STR     = "Sensor reading too high"
   SENSOR_READING_LOW          = 0x0309
   SENSOR_READING_LOW_STR      = "Sensor reading too low"
   SENSOR_CAL_PENDING          = 0x030A
   SENSOR_CAL_PENDING_STR      = "Calibrating sensor"
   SENSOR_CHANGE_CAL_ERROR     = 0x030B
   SENSOR_CHANGE_CAL_ERROR_STR = "Cal error - Change sensor"
   SENSOR_TIME_UNKNOWN         = 0x030C
   SENSOR_TIME_UNKNOWN_STR     = "Time unknown"
   SENSOR_LOST                 = 0
   SENSOR_LOST_STR             = "Lost connection to sensor"
